### ISSUE TITLE
Modeling `private(set) var` behavior using properties

### ISSUE THREAD

**Issue by zats** [ReactiveCocoa/ReactiveSwift#19]
Hi, I'm trying to figure out the best way to model behavior similar to

```swift
class Object {
  private(set) var property: Type

  func sideEffects() {
    property = newValue()
  }
}
```

when a function has side effects changing the value of the `property`.
The main goal of this exercise is to expose a readonly property that is modified from within the object using ReactiveSwift. My current setup looks like this:

```swift
class Object {
  let property: MutableProperty<Type>
  func sideEffects() {
    property.value = newValue()
  }
}
```
but that also allows changing property value from the outside of the object, e.g. `object.property.value = newUnexpectedValue()` which is what I want to avoid.

Thank you!

**Comment by andersio** [comment]
You may wrap it a public version of it as `Property`.

**Comment by ikesyo** [comment]
[Property](https://github.com/ReactiveCocoa/ReactiveSwift/blob/5fddc1f8e99b09d8f83029c8f2a52eab4e79dd6d/Sources/Property.swift#L362-L382) type would be what you want:

```swift
class Object {
  let _property: MutableProperty<Type>
  func sideEffects() {
    _property.value = newValue()
  }

  // Returns a read-only property that wraps an underlying property.
  var property: Property<Type> {
    return Property(_property)
  }
}
```

**Comment by zats** [comment]
Oh, thanks a lot @andersio and @ikesyo! Sorry for the beginner's questions 🙂

**Comment by robertjpayne** [comment]
Is there any room for discussion on this? This is one area of ReactiveSwift that really is unfortunate and ends up bloating code and requiring a large amount of boilerplate. 

I'd argue *most* properties are going to be read-only by default outside of the owner.

This could be solved pretty easily using a `struct` type for Property rather than a class type, I did this previously in RAC but can no longer do it with ReactiveSwift because `PropertyProtocol` now forces classes.

in RAC:

```
struct Property<Value>: PropertyType {
    
    var value: Value {
        get {
            return self.mutableProperty.value
        }
        set {
            self.mutableProperty.value = newValue
        }
    }
    
    private let mutableProperty: MutableProperty<Value>
    
    init(_ value: Value) {
        self.mutableProperty = MutableProperty(value)
    }
    
    var producer: SignalProducer<Value, NoError> {
        return self.mutableProperty.producer
    }
    
    var signal: Signal<Value, NoError> {
        return self.mutableProperty.signal
    }
    
}

```

and then

```
private(set) var name = Property<String>("Robert")
```

Was there a large amount of rationale around PropertyProtocol forcing classes now? I see the comment at the top of the file:

> Only classes can conform to this protocol, because having a signal for changes over time implies the origin must have a unique identity.

To me this is enforcing an ideological barrier, there's an initialiser that takes a signal and thus you've already created API that breaks this theory that the source is unique?

**Comment by andersio** [comment]
> Is there any room for discussion on this? This is one area of ReactiveSwift that really is unfortunate and ends up bloating code and requiring a large amount of boilerplate.

Sure. But I think the need of boilerplate should have been reduced by the introduction of property composition.

> This could be solved pretty easily using a struct type for Property rather than a class type, I did this previously in RAC but can no longer do it with ReactiveSwift because PropertyProtocol now forces classes.

Nothing is resolved IMO. The `Property` given here does not have real value semantics. What happens when you copy it? You get unintended sharing.

Of course alternatively, we can do CoW, so that each uniquely referenced copy has its own signal.

> >Only classes can conform to this protocol, because having a signal for changes over time implies the origin must have a unique identity.
>
> To me this is enforcing an ideological barrier, there's an initialiser that takes a signal and thus you've already created API that breaks this theory that the source is unique.

A property observing a signal or a producer is still unique, because the (produced) signal and the observation made to it is unique. It is not that it never has identity too, just that it was hid in RAC 4.0.
