### ISSUE TITLE
Port groupBy/uncollect from Rex to ReactiveSwift?

### ISSUE THREAD

**Issue by ynnckcmprnl** [ReactiveCocoa/ReactiveSwift#197]
[Rex](https://github.com/RACCommunity/Rex) contained a [groupBy](https://github.com/RACCommunity/Rex/blob/0.12.0/Source/SignalProducer.swift#L18) extension, which came in handy occasionally. With most of Rex' functionality moved to ReactiveCocoa, would it make sense to add/port the groupBy extension to ReactiveSwift?

I had a go myself at updating the groupBy extension to ReactiveSwift 1.0 & Swift 3.0 but couldn't quite make out how to address the removal of `SignalProducer.buffer(_ capacity: Int)`.

Another extension which might be worth adding/porting is uncollect, I can open a pull request if desired.

**Comment by andersio** [comment]
Would you mind to provide a reduced use case for both operators? New operators are definitely welcomed, just that we wanna keep it tight and straight.

`buffer(upTo:)` can be mimicked by:
```swift
let (signal, observer) = Signal<U, Error>.pipe()
let producer = SignalProducer(signal).replayLazily(upTo: n)
producer.start().dispose()
```

**Comment by andersio** [comment]
`uncollect` already exists as an overload of `flatten`, by the way.

**Comment by dmcrodrigues** [comment]
Regarding `uncollect` an almost equivalent is `flatten` available in ReactiveSwift for both `Signal` and `SignalProducer`. However, there's a constraint about the error type, `Error == NoError`, which is not defined on `uncollect` and removing it leads to an _Ambiguous use of 'flatMap(_:transform:)' which kind of makes sense since there are two versions of `flatMap` to accommodate both `Error` and `NoError`. I don't know if this was the reason behind this constraint but I don't see a reason to restrict this operator only for signals without errors.

Also, since we are talking about `flatten` as an alternative to `uncollect`, I'm having some difficulty to understand how relevant a strategy is to flatten a sequence, between picking `latest`, `merge`, or `concat` there's any difference?

**Comment by andersio** [comment]
Agree. The strategies do not matter when the inner sequence is immediate.

**Comment by dmcrodrigues** [comment]
@andersio If that's the case, maybe we can remove the strategy from `flatten` when the value is a `Sequence`? Introduces unnecessary confusion around the usage of the operator and can be misleading.

**Comment by mdiep** [comment]
> If that's the case, maybe we can remove the strategy from flatten when the value is a Sequence?

Yup, that makes sense to me. 👍 But it's too late to do it for 1.0. #198

> However, there's a constraint about the error type, Error == NoError, which is not defined on uncollect and removing it leads to an Ambiguous use of 'flatMap(:transform:)' which kind of makes sense since there are two versions of flatMap to accommodate both Error and NoError. I don't know if this was the reason behind this constraint but I don't see a reason to restrict this operator only for signals without errors.

I agree. The ambiguous use error can be worked around by annotating the types inside the operator.

```swift
extension SignalProtocol where Value: Sequence {
	/// Flattens the `sequence` value sent by `signal` according to
	/// the semantics of the given strategy.
	public func flatten(_ strategy: FlattenStrategy) -> Signal<Value.Iterator.Element, Error> {
		return self.flatMap(strategy) { SignalProducer<Value.Iterator.Element, Error>.init(values: $0) }
	}
}
```

Let's do this in #198 as well.

I'm not opposed to adding this functionality in 1.1 with the proviso that it would be removed in 2.0 in favor of `flatten`. (Since adding the operator can be done in a .x release as an additive change.)

**Comment by mdiep** [comment]
I'd definitely like to hear a concrete use case for `groupBy`. I know I've used something similar to that in the past, but I can't remember what for.

**Comment by iv-mexx** [comment]
In one of our projects we're using `groupBy` the following way:

We're tracking bluetooth beacons. Due to some limitations, all our beacons have the same UUID. We use the beacons major- and minor version to identify the beacon. 

We have a small wrapper that encapsulates all the beacon tracking API and exposes to us, simplified for the sake of the example, a `Signal<CLBeacon, NoError>`

When monitoring for beacons, we are 'in range' as long as there is at least one beacon with our UUID visible, but there might actually be several different beacons at the same time, or we might move from one beacon to one with overlapping region.

We are really interested in each beacon individually, but we have a signal of all beacons. Here, we use `groupBy` to separate this on signal into a separate signal for each individual beacon.

```
let allBeaconsSignal: Signal<CLBeacon, NoError>

allBeaconsSignal         
    .groupBy { beacon in return (beacon.major, beacon.minor) }
    .flatMap(.merge) { indidivualBeaconSignal in 
        // Do work with the signal for an individual beacon
    }
```

(Sorry for mistakes in the code, this example is just quickly typed here, in our app this is still written in ObjC 😸 )


Actually, I [have already ported `groupBy` from REX to Reactive Swift 1.0 (alpha 3) / Swift 3.0](https://github.com/RACCommunity/Rex/pull/159/files#diff-62aa425cf72f20c70aac8f69b7f3adbfR18), I could try to bring this over to ReactiveSwift instead.

**Comment by ynnckcmprnl** [comment]
I have used the groupBy & uncollect methods to group appointments per day for display in a `UICollectionView`, though there might be more elegant/shorter ways to achieve this.

```swift
SignalProducer(value: appointments)  
   .uncollect()  
   .groupBy { appointment in  
      appointment.begin.stripTime()  
    }  
   .map { $0.1.collect() }
   .flatten(.Concat)
   .collect()
}
```

**Comment by dmcrodrigues** [comment]
@ynnckcmprnl as a side note, by using`SignalProducer(values: appointments)` you can avoid `uncollect`, internally the producer will flatten your sequence by emitting each element.

**Comment by mdiep** [comment]
I think `groupBy` makes sense. It's a standard Rx operator, and it's not easy to build it yourself. 👍

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
