### ISSUE TITLE
Rename `Signal.observe(_:)`

### ISSUE THREAD

**Issue by dmcrodrigues** [ReactiveCocoa/ReactiveSwift#204]
`observe(_:)` is a helpful operator but I think the name can be misleading. Considering the following common pattern.

```swift
signal.observe(observer)
```

We may be induced to think the `signal` is observing `observer` and in fact it's the other way around (indirectly).

Introducing a named parameter could help to better express intent. 

```swift
signal.observe(using: observer)
signal.observe(on: observer)
```

However we already have `func observe(on scheduler: SchedulerProtocol)` which is something completely different. Another option could be renaming the operator to a completely different name and more close of the expected intent.

A few options I'm thinking.

```swift
signal.bind(observer)
signal.register(observer)
signal.subscribe(observer)
```

Does anyone agrees with this?

**Comment by andersio** [comment]
`observe` is an established term of art since the ObjC days, so as `start` since 3.0. I don't think we'd ever gonna change it.

Adding a preposition as label should be fairly enough to clarify the intent, and form grammatical phrases at the a use site (_Strive for Fluent Usage, Swift API Guidelines)_.

`with:` is also a contender — shorter than `using` but generally inferred by many to the same meaning.

**Comment by RuiAAPeres** [comment]
> observe is an established term of art since the ObjC days, so as start since 3.0. I don't think we'd ever gonna change them.

That's true, but on the other hand I liked these both:

```swift
signal.register(observer)
signal.subscribe(observer)
``` 

The `with:` label is probably a good mid ground.

**Comment by mdiep** [comment]
I think the key point is that you _observe_ a signal. So `observe` makes sense as the method name. That's clearest and it's a term of art.

I don't think a named parameter is necessary either. If we _did_ add a label, `with` or `using` seems most correct. But I think that draws attention away from the _observe_ part of the name.

**Comment by yoching** [comment]
I have same feelings about the misleading of the naming.
I always convert in my head
from
`
signal.observe(observer)
`
to
`
signal.observed(by: observer)
`

**Comment by liscio** [comment]
> I don't think a named parameter is necessary either. If we did add a label, with or using seems most correct. But I think that draws attention away from the observe part of the name.

@mdiep The trouble, though, is the most likely variable naming to follow as illustrated above. `observe(observer)` is far less readable than `observe(using: observer)`. Those that supply a trailing closure won't need to worry about the label…

Also, FWIW we talked about this briefly here: https://github.com/ReactiveCocoa/ReactiveSwift/pull/178#issuecomment-268997170

@yoching I really like `observed(by:)` except for the fact that you don't get a `Signal` out as a result. I think that's not going to work because it doesn't follow the API naming conventions.

**Comment by mdiep** [comment]
People seem pretty universally in favor of naming the parameter.

Looking at the Swift stdlib, `with` seems like a better fit. (`using` is only used with encoding.)

Does anyone think we shouldn't name the parameter? Does anyone think it should be something other than `with`?

**Comment by sharplet** [comment]
`with` works for me.

**Comment by liscio** [comment]
My trouble with `with` is the fact that it's the same word that is dropped from Objective-C API when imported by Swift. I prefer `using` because it's a verb rather than a preposition. Unfortunately, as @mdiep points out, `using` is rarely found in existing ObjC API so I'm OK with `with`.

(Random thought: If `Observer` was an honest-to-goodness object (one that could have methods of its own) then the solution would be obvious: we'd add `Observer.observe(_ signal: Signal<Value,Error>)` and all would make sense. I find it hard to find the inverse of that language—`getObserved(by:)` is beyond awkward, and again, `observed(by:)` won't work for API guideline reasons.)

**Comment by andersio** [comment]
@ReactiveCocoa/reactiveswift Hmm should we make a decision on this? It seems `observe(with:)` already got 5 votes.

**Comment by Qata** [comment]
`observe(with:)` seems clearer to me as well

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
