### ISSUE TITLE
NotificationCenter extension.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#36]
With the new signal lifetime semantics, we can safely express it as a `Signal<Notification, NoError>`. Any thoughts on changing it?

**Comment by mdiep** [comment]
That makes sense. 👍🏻

**Comment by NachoSoto** [comment]
The only reason all these extensions were `SignalProducer`s is because they were bridged from `RACSignal`, where we couldn't determine if they were hot.
I'm not too sure how this would be implemented, however, because we do need to remove the observer from `NSNotificationCenter`. Or maybe we can just rely on it being `weak` now?

**Comment by andersio** [comment]
The observer can be removed in the generator disposable of the signal.

**Comment by andersio** [comment]
Implemented in #64.
