### ISSUE TITLE
Async tests and TSan

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#458]
In our tests, many instances of async tests are being flagged by TSan as having data races. While they are safe in terms of the underlying hardware, we probably should still wrap all these variables with `Atomic`.

```swift
var isCompleted = false

signal
    .observe(on: QueueScheduler())
    .observeCompleted { isCompleted = true }
observer.sendCompleted()

expect(isCompleted).toEventually(equal(true))
```

**Comment by soxjke** [comment]
I would not use `Atomic` for this case. `Atomic` will definitely fix ThreadSanitizer issues. On other hand, it's also a part of testable unit so additional complexity is added due to testing part of solution by another part of solution.

While it might be good for descriptive purposes of how certain ReactiveSwift API's behave under particular test implications, I would generally change this to some kind of tests without side-effect.

To disclose my thought in a little bit more detailed view, let's take a closer look on what's tested here:
1. The subject-under-test is a `Signal` and its contract to deliver `completed` event to its subscribers when its `observer.sendCompleted()` is called.
2. To test this, the side effect of modifying local variable `isCompleted` is introduced.
3. What we are testing now: our newly introduced side effect is applied, thus `Signal`'s contract is executed
4. What should we test here: the actual `Signal`'s contract to call a closure passed to `observeCompleted`. For this purpose, we can pass some decorated closure to `observeCompleted` to verify it was called (with some retval, args, count etc.)

The example approach I'm suggesting is https://github.com/soxjke/Redux-ReactiveSwift/blob/master/Redux-ReactiveSwift/Tests/StoreSpec.swift#L74
It uses custom-made `CallSpy` within it: https://github.com/soxjke/Redux-ReactiveSwift/blob/master/Redux-ReactiveSwift/Tests/CallSpy.swift

I can prepare a test PR fixing some Thread Sanitizer issues using this approach if it fits into ReactiveSwift unit testing strategy.

**Comment by andersio** [comment]
True. This sounds a more scalable approach, in the sense that we may also assert a `dispatchPrecondition` with it & reuse it for all cases.

**Comment by soxjke** [comment]
Thanks! I'll give it a try during upcoming week.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
