### ISSUE TITLE
Replace `<~` operator with `bind(with:)`

### ISSUE THREAD

**Issue by gkaimakas** [ReactiveCocoa/ReactiveSwift#59]
Would it make sense to replace the `<~` operator with `bind(with:)`, then the api would become
````swift
mutableProperty.bind(with: someProducer)
````

That way the functionality will be discoverable from within Xcode and the user won't have to keep in mind that an operator exists.

**Comment by kaybutter** [comment]
The operator does express a direction though. The arrow tells you what goes where. The word "bind" doesn't really express a direction, even though the method probably won't setup a two-way binding. 🤔

**Comment by liscio** [comment]
Yeah, originally when I started out I was weary of the `<~` operator because it seemed strange. However, as @kaybutter raised it's difficult to express directionality without the operator—especially because bindings are (and will be for a long time) unidirectional.

We expect that new users will at least have some initial familiarity with the API (via the README, etc.) by the time they've started working with the framework so I'm not concerned that the operator will be *completely* foreign.
