### ISSUE TITLE
Parallelize work with RAS

### ISSUE THREAD

**Issue by jjoelson** [ReactiveCocoa/ReactiveSwift#638]
The APIContracts doc [offhandedly mentions](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/APIContracts.md#avoid-introducing-concurrency) that "ReactiveSwift offers built-in ways to parallelize work." What is this referring to? The [documentation for `QueueScheduler`](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Scheduler.swift#L227) says:

> Even if the queue is concurrent, all work items enqueued with the `QueueScheduler` will be serial with respect to each other.

Is there some other mechanism that can be used to parallelize work with `ReactiveSwift`?

**Comment by mdiep** [comment]
Check out `flatMap` and `FlattenStrategy`.

**Comment by jjoelson** [comment]
`flatMap` let's you control how a series of asynchronous producers are started, but that seems different from actually scheduling parallel CPU work. I'm envisioning a scenario where I have a bunch of producers who's `startHandler`s perform synchronous long-running CPU bound work. As far as I know, `flatMap` just starts incoming producers synchronously regardless of the `FlattenStrategy`, and it's left up to the producer to determine how it's work is actually scheduled. 

What I'm talking about is something like `start(on:)` which controls the actual execution of the `startHandler` , except there doesn't appear to be any concurrent `Scheduler` to use there.

**Comment by mdiep** [comment]
You're right that `flatMap` doesn't introduce concurrency. That's probably not what you'd want in most circumstances as certain producers might be required to run on certain schedulers.

The general idea is to run producers on different serials queues as necessary and then `flatMap`ing them into a concurrent producer instead of using a concurrent queue. It's hard to give good guidance on this generally.

**Comment by jjoelson** [comment]
@mdiep, would it make sense to manually have producers start work on a concurrent GCD queue, bypassing the RAS `Scheduler` abstraction entirely? E.g.:

```swift
extension SignalProducer {
    func start(on queue: DispatchQueue) {
        return SignalProducer { observer, lifetime in
            queue.async {
	        lifetime += self.start(observer)
	    }
	}
    }
}

let input: Signal<String, NoError> = ...

input
    .flatMap(.merge) { str in
        return getProducer(str)
            .start(on: queue.global(qos: .userInitiated))
    }
    .observeValues { val in
        // Do something
    }
```

Or would this mess things up internally with respect to serial event delivery?

**Comment by mdiep** [comment]
That would cause issues.

**Comment by liscio** [comment]
I've been thinking about parallel operations + ReactiveSwift a lot over the years, and the only solution I've come up with (but have yet to exercise in a major way) involves an array of inner `SignalProducer`s that ultimately dispatch their work to a collection of schedulers. Almost like a thread pool, but managed differently.

As far as your issue with start() running on the main queue, @jjoelson: you must be careful to use the correct construct when building your `SignalProducer`. A while ago in #240 I introduced the initializer variant that eventually became `public init(_ action: @escaping () -> Value)` to solve this exact issue.

Using that with `start(on: Scheduler)` should allow you to create a signal producer that invokes its start method on a given scheduler rather than at the point of creation. Using `lazyMap` gives you a similar construct in the case where that operator makes more sense.

This approach is especially useful because you can cancel the returned SignalProducer before the `action` ever executes on its target dispatch queue. This eliminates a great deal of "thread explosion" errors that I've encountered before I had this construct available to me.

**Comment by jjoelson** [comment]
@sharplet, that's very good to know, thanks.

**Comment by liscio** [comment]
> The case I'm thinking of here is any kind of CPU-bound task. For example, imagine some kind of image processing that takes 1 second per image. If you have 90 images to process, it will take about a minute and a half to complete if performed serially. But on a multi-core system you can potentially finish much faster.

I get what you're saying, but just want to point out that—unless you have a very complex front-end that feeds already-loaded images into RAM—most commonly-performed image processing is I/O bound. This leads to a massive creation of new threads when performed on a concurrent queue. See below for a sample of this exact issue.

> […] a concurrent queue will generally be smart about deciding how many tasks to start simultaneously in order to maximize performance

Nope. They're not even a little bit smart about that once you introduce I/O. In fact, they would happily *lock up your system* in this scenario. See "Extra Info" below.

> With respect to using a group of serial queues as a "thread pool", the documentation explicitly recommends against that

It recommends against creating *large numbers* of them, sure. But 6-10? Not that big a deal, and less of a problem if they all target the same destination queue. At any rate, let's just address the major problem with concurrent queues, which is their effectively-unbounded nature of operation.

> So it's not clear to me why allowing users to easily dump tasks onto a concurrent DispatchQueue like with `subscribeOn(ConcurrentDispatchQueueScheduler(qos: .userInitiated))` is shooting themselves in the foot, but as I said, my knowledge of GCD is limited.

Check out the following repository: [ConcurrentTest](https://github.com/liscio/ConcurrentTest). It demonstrates exactly the problem that is caused by "allowing users to easily dump tasks onto a concurrent `DispatchQueue`."

Run it once to completion just to see it work. Then, change `goCrazyWithThreads = true` in `main.swift` and run it again—execution should halt. Pause the debugger, and look at how many threads got created. **This is precisely the problem I am speaking about**.

While I think that it'd be *nice* to have a concurrent scheduler type for certain circumstances, I think they would introduce far more problems than they solve. If someone's trying to wrap their head around reactive programming, we don't want to have them introduce issues that *appear to be deadlocks* but are actually caused by an explosion of threads due to a fundamental misunderstanding of how dispatch queues actually work.

So for now, if you're looking to do long-ish running concurrent work then the way I demonstrate it in [ConcurrentTest](https://github.com/liscio/ConcurrentTest) is probably a good place to start.

#### Extra Info

[This article from Mike Ash](https://www.mikeash.com/pyblog/friday-qa-2009-09-25-gcd-practicum.html) also covers this issue very well. Note that in the article he employs a semaphore to help cap the # of threads that get created by the system.

In `ReactiveSwift`, we can use the `.concurrent` flattening strategy to achieve something very similar, as demonstrated by my [ConcurrentTest](https://github.com/liscio/ConcurrentTest) project.

**Comment by jjoelson** [comment]
@liscio, thanks for that example, I think a concurrent queue in conjunction with the `concurrent` flatten strategy is exactly what I'm looking for. I also think your explanation for why there's no built-in operator to execute a producer's work on a concurrent queue makes perfect sense. You'd almost have to build it into a `FlattenStrategy` to ensure that it was never misused.

**Comment by liscio** [comment]
@sharplet is correct that `concurrentPerform` will behave much more smartly than just firing blocks at a background queue. You can ask it to charge through thousands of iterations, and even when I/O is involved it won't blow up on you.

However, its utility is limited to scenarios where you have a fixed data set to process. For instance, while scrolling by in a collection or table view, you might want to send thumbnail images to process concurrently in the background (and you especially want to cancel their operation when the cells scroll out of view.

Treat `concurrentPerform` (and its underlying, `dispatch_apply`) as the equivalent to a `for` loop. You have access to a prepared set of data that you wish to process in parallel, all at once.

Just keep the following in mind:

* Execute your `concurrentPerform` blocks on a serial queue. The same explosions can still occur if you just toss batches of `concurrentPerform` calls onto the global queue.

* There's no easy way to cancel their work once they're started.

* They're not cheap to create, so make sure the work you schedule is substantial enough to warrant parallelizing in this way (e.g. don't just multiply pairs of numbers together.)
