### ISSUE TITLE
DynamicProperty not exist

### ISSUE THREAD

**Issue by tuzaiz** [ReactiveCocoa/ReactiveSwift#67]
Hi, 

Does the DynamicProperty be removed? My Xcode shows `Use of unresolved identifier 'DynamicProperty'` for all lines with DynamicProperty.

I wonder how to observe the value change and bind with view model now? Thanks

**Comment by andersio** [comment]
`DynamicProperty` belongs to ReactiveCocoa, since it is Cocoa specific.

To observe KVO changes, ReactiveCocoa now provides a plain and simple `NSObject.reactive.values(forKeyPath:)`, in addition to `DynamicProperty`. As for bindings, ReactiveCocoa now includes a comprehensive set of reactive extensions to AppKit and UIKit components, accessible via `.reactive`.

Please check https://github.com/ReactiveCocoa/ReactiveCocoa/ for more information.

**Comment by tuzaiz** [comment]
Thanks for @andersio answer, but how could I fix the code like this?

`DynamicProperty(object: nameLabel, keyPath: "text") <~ viewModel.name.producer`

**Comment by andersio** [comment]
`DynamicProperty` is parameterized in 5.0. Specialize it with the expected type.

Alternatively, use the new reactive extensions.

```
DynamicProperty<String>(object: nameLabel, keyPath: "text") <~ viewModel.name.producer

nameLabel.reactive.text <~ viewModel.name.producer
```

**Comment by tuzaiz** [comment]
Yeah~ it works. One more question please.

How could I bind text value of textField to property?

I tried this but it shows `Ambiguous reference to member 'textValues'`

`self.viewModel.title <~ self.titleField.reactive.textValues`

**Comment by andersio** [comment]
Is `Value` of your `title` non-optional? You need to deal with the optionality. You can do `optional <~ (optional | non-optional)`, but never `non-optional <~ optional`.
