### ISSUE TITLE
Is there a filter(while:)?

### ISSUE THREAD

**Issue by arnopoulos** [ReactiveCocoa/ReactiveSwift#670]
I have a `Signal` where I want it to drop events if another `Property<Bool>` is false. Is there something that is built into ReactiveSwift to help me accomplish this?

**Comment by sharplet** [comment]
You might be able to try `signal.throttle(while: property.negate())`.

**Comment by arnopoulos** [comment]
@sharplet I thought that `throttle` just delays the execution of events? If so, I think what I need is a `debounce(while:)` of `filter(while:)`

**Comment by sharplet** [comment]
Yeah, `throttle(while:)` will drop everything but the most recent event.

Here's a quick sketch of how I would compose this out of existing operators:

```swift
enum MyEvent {
  case foo(Foo)
  case enabledChanged(Bool)
}

struct MyState {
  var foo: Foo?

  var isEnabled: Bool {
    didSet {
      if !isEnabled {
        foo = nil
      }
    }
  }

  static let initial = MyState(foo: nil, isEnabled: true)
}

let fooEvents = foo.map(MyEvent.foo)
let enabledChanged = isEnabled.map(MyEvent.enabledChanged)

let fooWhileEnabled = SignalProducer
  .merge([fooEvents, enabledChanged])
  .scan(into: MyState.initial) { state, event in
    switch event {
    case let .foo(foo):
      state.foo = foo
    case let .enabledChanged(isEnabled):
      state.isEnabled = isEnabled
    }
  }
  .filterMap { $0.foo }
```

So the key things are:

1. Create some kind of `Event` enum to convert all your inputs to the same type;
2. Use `scan()` to combine incoming events into some kind of state value;
3. Use `filterMap()` to drop states that you don't want, and keep states that you do.

It should be straight-forward to generalise the `MyEvent` and `MyState` types into generics so that this operation is reusable for different types.

**Comment by arnopoulos** [comment]
@sharplet That worked! Thanks for your help.
