### ISSUE TITLE
Unexpected behaviour when using debounce operator

### ISSUE THREAD

**Issue by vrutberg** [ReactiveCocoa/ReactiveSwift#718]
Hi,

First of all, I'd like to clarify that I don't know if the behaviour this ticket describes is expected behaviour or not. For me it lead to a bug that was quite hard to track down and it's not apparent to me why this occurs, so to me it is unexpected. :-)

Anyhow, consider this code:

```swift
import ReactiveSwift

let string = MutableProperty<String?>(nil)
let scheduler = TestScheduler()

let debouncedString = string.producer.debounce(0.1, on: scheduler)

let first = Property<String?>(initial: nil, then: debouncedString)
let second = Property<String?>(initial: nil, then: debouncedString)

second.producer.startWithValues {
    print("second: \($0)")
}

string.value = "Test"
scheduler.advance(by: .seconds(1))
```

I would expect that it would print this:

```
second: nil
second: Optional("Test")
```

However, when the `debounceString` property is given to two `Property` instances *and* it is debounced, only the first property will be given the debounced values of `debounceString`.

The actual output of the code above is this:

```
second: nil
```

Is this a bug? Or am I missing something?

I'm using ReactiveSwift 4.0.0.

Thanks.

**Comment by mdiep** [comment]
`0.1` seconds haven't elapsed since the initial subscription (the first value on `string`) and the `string.value = "Test"`(the second value on `string`)—so debounce is doesn't exactly what debounce is supposed to do, only send the second value.

If 0.1 seconds passed before you sent the second value, then both would be sent on the debounced signal.

**Comment by vrutberg** [comment]
I'm not sure that's what happening here. Let me clarify my example:

```swift
import ReactiveSwift

let string = MutableProperty<String?>(nil)
let scheduler = TestScheduler()

let debouncedString = string.producer.debounce(0.1, on: scheduler)

let firstProperty = Property<String?>(initial: nil, then: debouncedString)
let secondProperty = Property<String?>(initial: nil, then: debouncedString)

firstProperty.producer.startWithValues {
    print("first property value: \($0)")
}

secondProperty.producer.startWithValues {
    print("second property value: \($0)")
}

string.value = "Test"
scheduler.advance(by: .seconds(1))
```

This will print:

```
first property value: nil
second property value: nil
first property value: Optional("Test")
```

The thing I find unexpected is that the value `Test` never reaches `secondProperty`. Since both properties are subscribed to the same SignalProducer I would assume that they receive the same values. Are you saying that this is the expected behaviour?

**Comment by vrutberg** [comment]
If `debouncedString` is changed to a `signal` (i.e. `let debouncedString = string.signal.debounce(0.1, on: scheduler)`) this works as I would expect.

**Comment by gpambrozio** [comment]
I just found something similar on my project and I believe `debounce` to be broken when you start a producer twice. With latest master, I added the following tests to `SignalProducerSpec.swift` and they both fail (just the second expectation of each `it`, not the first):

```
		describe("debounce") {
			context("property - starting twice") {
				it("should deliver the same values") {
					let p1 = MutableProperty(1)
					let p2 = MutableProperty(2)

					let scheduler = TestScheduler()
					let combined = Property.combineLatest(p1, p2)
					let prod = combined
						.producer
						.skipRepeats { $0 == $1 }
						.map { $0 + $1 }
						.debounce(0.1, on: scheduler)

					var v1 = [Int]()
					var v2 = [Int]()
					prod.startWithValues { (v) in
						v1.append(v)
					}
					prod.startWithValues { (v) in
						v2.append(v)
					}

					scheduler.advance(by: .milliseconds(200))
					p1.value = 3
					scheduler.advance(by: .milliseconds(200))
					p2.value = 4
					scheduler.advance(by: .milliseconds(200))
					p2.value = 4
					scheduler.advance(by: .milliseconds(200))

					expect(v1).to(equal([3, 5, 7]))
					expect(v2).to(equal([3, 5, 7]))
				}
			}

			context("pipe - starting twice") {
				it("should deliver the same values") {
					let p1 = SignalProducer<Int, Never>.pipe()
					let p2 = SignalProducer<Int, Never>.pipe()

					let scheduler = TestScheduler()
					let combined = SignalProducer.combineLatest(p1.0, p2.0)
					let prod = combined
						.skipRepeats { $0 == $1 }
						.map { $0 + $1 }
						.debounce(0.1, on: scheduler)

					var v1 = [Int]()
					var v2 = [Int]()
					prod.startWithValues { (v) in
						v1.append(v)
					}
					prod.startWithValues { (v) in
						v2.append(v)
					}

					p1.1.send(value: 1)
					p2.1.send(value: 2)
					scheduler.advance(by: .milliseconds(200))
					p1.1.send(value: 3)
					scheduler.advance(by: .milliseconds(200))
					p2.1.send(value: 4)
					scheduler.advance(by: .milliseconds(200))
					p2.1.send(value: 4)
					scheduler.advance(by: .milliseconds(200))

					expect(v1).to(equal([3, 5, 7]))
					expect(v2).to(equal([3, 5, 7]))

				}
			}
		}
```

If you remove the `debounce` from the chain they succeed.

I understand why changing it to a `Signal` would fix this but shouldn't this work for this case as well?

I noticed this on one of my projects after I updated `ReactiveSwift` from 3.1 to 6.2. On 3.1 this was working as I'd expect but on 6.1 my feature broke because of this.

I'm afraid it might be because of [this change](https://github.com/ReactiveCocoa/ReactiveSwift/pull/605) as this is the only change regarding `debounce` on the changelog but I have not confirmed that yet.

**Comment by gpambrozio** [comment]
Since this issue is closed I'll start a new one so.
