### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by kenshinzz** [ReactiveCocoa/ReactiveSwift#779]
I found this issue when I build with xcode 11.4.1

ReactiveSwift version 6.1

<img width="1002" alt="Screen Shot 2563-04-30 at 14 22 19" src="https://user-images.githubusercontent.com/19835819/80683324-3d172d00-8aee-11ea-888c-ac9d633a95ea.png">

**Comment by Marcocanc** [comment]
Have you tried rebuilding ReactiveSwift since downloading/installing 11.4.1?

**Comment by kenshinzz** [comment]
Yes, I have

**Comment by andersio** [comment]
We haven't distributed binaries since ReactiveSwift 2.0. This looks more a Carthage related issue, which Carthage builds your dependencies using a different Xcode version (and hence Swift compiler). Try to make sure that the `xcode-select` is pointing to the version you actually intended to use.

https://github.com/Carthage/Carthage/issues

**Comment by ikesyo** [comment]
We will need to set `BUILD_LIBRARIES_FOR_DISTRIBUTION` to `YES` for supporting module stability introduced in Swift 5.1.

**Comment by andersio** [comment]
@ikesyo Could you please elaborate on the rationle?

Users embedding ReactiveSwift as source libraries shouldn't be required to pay the cost for `BUILD_LIBRARIES_FOR_DISTRIBUTION`, should they? That is unless you are advocating for us to start formally guaranteeing ABI and module stability?

**Comment by ikesyo** [comment]
Otherwise Carthage users who build frameworks locally can't reuse built frameworks. Hmm should Carthage offer `--build-for-distribution` option for this situation? 🤔
