### ISSUE TITLE
Playground doesn't work in Xcode 12

### ISSUE THREAD

**Issue by iby** [ReactiveCocoa/ReactiveSwift#803]
I can't run macOS and iOS playgrounds, the same is happening with ReactiveCocoa. Tried cleaning the project and purging the entire derived data folders – no luck. Any ideas why?

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/1086845/94174346-34146700-fea6-11ea-93f9-a0fcccaba72e.png">

I used it just a few weeks ago before getting Xcode 12. Relevant frameworks are successfully built prior attempting to run the playground. Using workspace, not project.

**Comment by ianbytchek** [comment]
Seems like this is caused by `Build Active Scheme` not being enabled by default (despite manually building it prior running the playground).

<img width="269" alt="image" src="https://user-images.githubusercontent.com/1086845/95049792-83a33000-06fb-11eb-98c4-046c4ee8bd37.png">

Apparently this configuration is stored in user `xcuserdata` in `UserInterfaceState.xcuserstate` which is Git-ignored. Unless there's a way to share the configuration, perhaps the best thing to do for both ReactiveSwift and ReactiveCocoa is to update playground header documentation. 

I'm happy to send a PR, please let know if that's indeed the best solution?

**Comment by jhirsh** [comment]
That worked for me! 

Playground header documentation is a good place for it

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
